// Preloader
export const PRELOADER_TOGGLE = 'PRELOADER_TOGGLE'

// Product
export const LOAD_PRODUCTS = 'LOAD_PRODUCTS'
export const LOAD_PRODUCT = 'LOAD_PRODUCT'
export const CREATE_PRODUCT = 'CREATE_PRODUCT'
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT'
export const DELETE_PRODUCT = 'DELETE_PRODUCT'
export const PRODUCTS_TOGGLE = 'PRODUCTS_TOGGLE'
export const PRODUCT_TOGGLE = 'PRODUCT_TOGGLE'
export const LOAD_VARIANT = 'LOAD_VARIANT'
export const LOAD_VARIANTS = 'LOAD_VARIANTS'

// Template
export const LOAD_TEMPLATES = 'LOAD_TEMPLATES'
export const LOAD_TEMPLATE = 'LOAD_TEMPLATE'
export const CREATE_TEMPLATE = 'CREATE_TEMPLATE'
export const UPDATE_TEMPLATE = 'UPDATE_TEMPLATE'
export const DELETE_TEMPLATE = 'DELETE_TEMPLATE'
export const TEMPLATES_TOGGLE = 'TEMPLATES_TOGGLE'
export const TEMPLATE_TOGGLE = 'TEMPLATE_TOGGLE'

// Attribute
export const LOAD_ATTRIBUTES = 'LOAD_ATTRIBUTES'
export const SEARCH_ATTRIBUTES = 'SEARCH_ATTRIBUTES'
export const LOAD_ATTRIBUTE = 'LOAD_ATTRIBUTE'
export const LIST_STORE = 'LIST_STORE'
export const CREATE_ATTRIBUTE = 'CREATE_ATTRIBUTE'
export const UPDATE_ATTRIBUTE = 'UPDATE_ATTRIBUTE'
export const DELETE_ATTRIBUTE = 'DELETE_ATTRIBUTE'
export const ATTRIBUTES_TOGGLE = 'ATTRIBUTES_TOGGLE'
export const ATTRIBUTE_TOGGLE = 'ATTRIBUTE_TOGGLE'

// Freight Option
export const LOAD_FREIGHTOPTIONS = 'LOAD_FREIGHTOPTIONS'
export const LOAD_FREIGHTOPTION = 'LOAD_FREIGHTOPTION'
export const CREATE_FREIGHTOPTION = 'CREATE_FREIGHTOPTION'
export const UPDATE_FREIGHTOPTION = 'UPDATE_FREIGHTOPTION'
export const DELETE_FREIGHTOPTION = 'DELETE_FREIGHTOPTION'
export const FREIGHTOPTIONS_TOGGLE = 'FREIGHTOPTIONS_TOGGLE'
export const FREIGHTOPTION_TOGGLE = 'FREIGHTOPTION_TOGGLE'

// Vendor
export const LOAD_VENDORS = 'LOAD_VENDORS'
export const LOAD_VENDOR = 'LOAD_VENDOR'
export const CREATE_VENDOR = 'CREATE_VENDOR'
export const UPDATE_VENDOR = 'UPDATE_VENDOR'
export const DELETE_VENDOR = 'DELETE_VENDOR'
export const VENDORS_TOGGLE = 'VENDORS_TOGGLE'
export const VENDOR_TOGGLE = 'VENDOR_TOGGLE'

// Toaster
export const TOAST_TOGGLE = 'TOAST_TOGGLE'
